<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TodoApp.Core\TodoApp.Core.csproj" />
    <ProjectReference Include="..\TodoApp.Services\TodoApp.Services.csproj" />
    <ProjectReference Include="..\TodoApp.UI\TodoApp.UI.csproj" />
    <ProjectReference Include="..\TodoApp.DAL\TodoApp.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
